// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sql

import (
	"context"
)

const delete = `-- name: Delete :exec
DELETE FROM user_settings
WHERE chatid = $1 and  id = $2
`

type DeleteParams struct {
	Chatid int64 `db:"chatid"`
	ID     int64 `db:"id"`
}

func (q *Queries) Delete(ctx context.Context, db DBTX, arg *DeleteParams) error {
	_, err := db.Exec(ctx, delete, arg.Chatid, arg.ID)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, chatid, name, auth_code::text, step::text FROM user_settings
`

type GetAllRow struct {
	ID       int64  `db:"id"`
	Chatid   int64  `db:"chatid"`
	Name     string `db:"name"`
	AuthCode string `db:"auth_code"`
	Step     string `db:"step"`
}

func (q *Queries) GetAll(ctx context.Context, db DBTX) ([]*GetAllRow, error) {
	rows, err := db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Chatid,
			&i.Name,
			&i.AuthCode,
			&i.Step,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, name, auth_code::text, step::text FROM user_settings WHERE chatid = $1
`

type GetByIdRow struct {
	ID       int64  `db:"id"`
	Name     string `db:"name"`
	AuthCode string `db:"auth_code"`
	Step     string `db:"step"`
}

func (q *Queries) GetById(ctx context.Context, db DBTX, chatid int64) (*GetByIdRow, error) {
	row := db.QueryRow(ctx, getById, chatid)
	var i GetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AuthCode,
		&i.Step,
	)
	return &i, err
}

const insert = `-- name: Insert :one
INSERT INTO user_settings (
    chatid, name, auth_code, step
) VALUES (
             $1, $2, $3::text, $4::text
         ) returning id
`

type InsertParams struct {
	Chatid   int64  `db:"chatid"`
	Name     string `db:"name"`
	AuthCode string `db:"auth_code"`
	Step     string `db:"step"`
}

func (q *Queries) Insert(ctx context.Context, db DBTX, arg *InsertParams) (int64, error) {
	row := db.QueryRow(ctx, insert,
		arg.Chatid,
		arg.Name,
		arg.AuthCode,
		arg.Step,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const update = `-- name: Update :exec
UPDATE user_settings
SET  name = $1, auth_code = $2::text, step = $3::text
WHERE chatid = $4
`

type UpdateParams struct {
	Name     string `db:"name"`
	AuthCode string `db:"auth_code"`
	Step     string `db:"step"`
	Chatid   int64  `db:"chatid"`
}

func (q *Queries) Update(ctx context.Context, db DBTX, arg *UpdateParams) error {
	_, err := db.Exec(ctx, update,
		arg.Name,
		arg.AuthCode,
		arg.Step,
		arg.Chatid,
	)
	return err
}
