// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql

import (
	"context"
)

const delete = `-- name: Delete :exec
DELETE FROM user_settings
WHERE chatid = $1 and  id = $2
`

type DeleteParams struct {
	Chatid int64 `db:"chatid"`
	ID     int64 `db:"id"`
}

func (q *Queries) Delete(ctx context.Context, db DBTX, arg *DeleteParams) error {
	_, err := db.Exec(ctx, delete, arg.Chatid, arg.ID)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, chatid, name, settings, step::text, status,premium FROM user_settings
`

type GetAllRow struct {
	ID       int64  `db:"id"`
	Chatid   int64  `db:"chatid"`
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
}

func (q *Queries) GetAll(ctx context.Context, db DBTX) ([]*GetAllRow, error) {
	rows, err := db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Chatid,
			&i.Name,
			&i.Settings,
			&i.Step,
			&i.Status,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, name, settings, step::text,status,premium FROM user_settings WHERE chatid = $1
`

type GetByIdRow struct {
	ID       int64  `db:"id"`
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
}

func (q *Queries) GetById(ctx context.Context, db DBTX, chatid int64) (*GetByIdRow, error) {
	row := db.QueryRow(ctx, getById, chatid)
	var i GetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.Step,
		&i.Status,
		&i.Premium,
	)
	return &i, err
}

const insert = `-- name: Insert :one
INSERT INTO user_settings (
    chatid, name, settings, step, status,premium
) VALUES (
             $1, $2, $3, $4::text, $5, $6
         ) returning id
`

type InsertParams struct {
	Chatid   int64  `db:"chatid"`
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
}

func (q *Queries) Insert(ctx context.Context, db DBTX, arg *InsertParams) (int64, error) {
	row := db.QueryRow(ctx, insert,
		arg.Chatid,
		arg.Name,
		arg.Settings,
		arg.Step,
		arg.Status,
		arg.Premium,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEnabled = `-- name: ListEnabled :many
SELECT id, chatid, name, settings, step, status, premium
FROM user_settings
WHERE status = true
`

func (q *Queries) ListEnabled(ctx context.Context, db DBTX) ([]*UserSetting, error) {
	rows, err := db.Query(ctx, listEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserSetting
	for rows.Next() {
		var i UserSetting
		if err := rows.Scan(
			&i.ID,
			&i.Chatid,
			&i.Name,
			&i.Settings,
			&i.Step,
			&i.Status,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE user_settings
SET  name = $1, settings = $2, step = $3::text, status = $4,premium = $5
WHERE chatid = $6
`

type UpdateParams struct {
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
	Chatid   int64  `db:"chatid"`
}

func (q *Queries) Update(ctx context.Context, db DBTX, arg *UpdateParams) error {
	_, err := db.Exec(ctx, update,
		arg.Name,
		arg.Settings,
		arg.Step,
		arg.Status,
		arg.Premium,
		arg.Chatid,
	)
	return err
}
