// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeTrade = `-- name: CloseTrade :exec
UPDATE trade_history
SET
    exit_price = $2,
    exit_size = $3,
    exit_at = $4,
    realized_pnl = $5,
    realized_pnl_pct = $6,
    close_reason = $7,
    status = 'closed',
    updated_at = now()
WHERE guid = $1
  AND status = 'open'
`

type CloseTradeParams struct {
	Guid           pgtype.UUID        `db:"guid"`
	ExitPrice      float64            `db:"exit_price"`
	ExitSize       float64            `db:"exit_size"`
	ExitAt         pgtype.Timestamptz `db:"exit_at"`
	RealizedPnl    float64            `db:"realized_pnl"`
	RealizedPnlPct float64            `db:"realized_pnl_pct"`
	CloseReason    string             `db:"close_reason"`
}

func (q *Queries) CloseTrade(ctx context.Context, db DBTX, arg *CloseTradeParams) error {
	_, err := db.Exec(ctx, closeTrade,
		arg.Guid,
		arg.ExitPrice,
		arg.ExitSize,
		arg.ExitAt,
		arg.RealizedPnl,
		arg.RealizedPnlPct,
		arg.CloseReason,
	)
	return err
}

const createTrade = `-- name: CreateTrade :exec
INSERT INTO trade_history (
    guid, user_id, inst_id, pos_side, side, timeframe, strategy,
    entry_price, entry_size, entry_at,
    stop_loss, take_profit, leverage,
    open_order_id, algo_id,
    status, created_at, updated_at
) VALUES (
             $1,$2,$3,$4,$5,$6,$7,
             $8,$9,$10,
             $11,$12,$13,
             $14,$15,
             $16,now(),now()
         )
`

type CreateTradeParams struct {
	Guid        pgtype.UUID        `db:"guid"`
	UserID      int64              `db:"user_id"`
	InstID      string             `db:"inst_id"`
	PosSide     string             `db:"pos_side"`
	Side        string             `db:"side"`
	Timeframe   string             `db:"timeframe"`
	Strategy    string             `db:"strategy"`
	EntryPrice  float64            `db:"entry_price"`
	EntrySize   float64            `db:"entry_size"`
	EntryAt     pgtype.Timestamptz `db:"entry_at"`
	StopLoss    float64            `db:"stop_loss"`
	TakeProfit  float64            `db:"take_profit"`
	Leverage    int32              `db:"leverage"`
	OpenOrderID string             `db:"open_order_id"`
	AlgoID      string             `db:"algo_id"`
	Status      string             `db:"status"`
}

func (q *Queries) CreateTrade(ctx context.Context, db DBTX, arg *CreateTradeParams) error {
	_, err := db.Exec(ctx, createTrade,
		arg.Guid,
		arg.UserID,
		arg.InstID,
		arg.PosSide,
		arg.Side,
		arg.Timeframe,
		arg.Strategy,
		arg.EntryPrice,
		arg.EntrySize,
		arg.EntryAt,
		arg.StopLoss,
		arg.TakeProfit,
		arg.Leverage,
		arg.OpenOrderID,
		arg.AlgoID,
		arg.Status,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM user_settings
WHERE chatid = $1 and  id = $2
`

type DeleteParams struct {
	Chatid int64 `db:"chatid"`
	ID     int64 `db:"id"`
}

func (q *Queries) Delete(ctx context.Context, db DBTX, arg *DeleteParams) error {
	_, err := db.Exec(ctx, delete, arg.Chatid, arg.ID)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, chatid, name, settings, step::text, status,premium FROM user_settings
`

type GetAllRow struct {
	ID       int64  `db:"id"`
	Chatid   int64  `db:"chatid"`
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
}

func (q *Queries) GetAll(ctx context.Context, db DBTX) ([]*GetAllRow, error) {
	rows, err := db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllRow
	for rows.Next() {
		var i GetAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Chatid,
			&i.Name,
			&i.Settings,
			&i.Step,
			&i.Status,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, name, settings, step::text,status,premium FROM user_settings WHERE chatid = $1
`

type GetByIdRow struct {
	ID       int64  `db:"id"`
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
}

func (q *Queries) GetById(ctx context.Context, db DBTX, chatid int64) (*GetByIdRow, error) {
	row := db.QueryRow(ctx, getById, chatid)
	var i GetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Settings,
		&i.Step,
		&i.Status,
		&i.Premium,
	)
	return &i, err
}

const getTradeStats = `-- name: GetTradeStats :one
SELECT
    COUNT(*) AS total_trades,
    COUNT(*) FILTER (WHERE status = 'open') AS open_trades,
    COUNT(*) FILTER (WHERE status = 'closed') AS closed_trades,

    COUNT(*) FILTER (WHERE status = 'closed' AND realized_pnl > 0) AS wins,
    COUNT(*) FILTER (WHERE status = 'closed' AND realized_pnl < 0) AS losses,

    COALESCE(SUM(realized_pnl) FILTER (WHERE status = 'closed'), 0)::double precision AS total_pnl,
    COALESCE(AVG(realized_pnl) FILTER (WHERE status = 'closed'), 0)::double precision  AS avg_pnl,
    COALESCE(AVG(realized_pnl) FILTER (WHERE status = 'closed' AND realized_pnl > 0), 0)::double precision  AS avg_win,
    COALESCE(AVG(realized_pnl) FILTER (WHERE status = 'closed' AND realized_pnl < 0), 0)::double precision  AS avg_loss,

    COUNT(*) FILTER (WHERE status = 'closed' AND close_reason = 'tp') AS tp_count,
    COUNT(*) FILTER (WHERE status = 'closed' AND close_reason = 'sl') AS sl_count,
    COUNT(*) FILTER (WHERE status = 'closed' AND close_reason = 'time_stop') AS time_stop_count,
    COUNT(*) FILTER (WHERE status = 'closed' AND close_reason = 'partial') AS partial_count,
    COUNT(*) FILTER (WHERE status = 'closed' AND close_reason = 'manual') AS manual_count,
    COUNT(*) FILTER (WHERE status = 'closed' AND close_reason = 'unknown') AS unknown_count
FROM trade_history
WHERE user_id = $1
`

type GetTradeStatsRow struct {
	TotalTrades   int64   `db:"total_trades"`
	OpenTrades    int64   `db:"open_trades"`
	ClosedTrades  int64   `db:"closed_trades"`
	Wins          int64   `db:"wins"`
	Losses        int64   `db:"losses"`
	TotalPnl      float64 `db:"total_pnl"`
	AvgPnl        float64 `db:"avg_pnl"`
	AvgWin        float64 `db:"avg_win"`
	AvgLoss       float64 `db:"avg_loss"`
	TpCount       int64   `db:"tp_count"`
	SlCount       int64   `db:"sl_count"`
	TimeStopCount int64   `db:"time_stop_count"`
	PartialCount  int64   `db:"partial_count"`
	ManualCount   int64   `db:"manual_count"`
	UnknownCount  int64   `db:"unknown_count"`
}

func (q *Queries) GetTradeStats(ctx context.Context, db DBTX, userID int64) (*GetTradeStatsRow, error) {
	row := db.QueryRow(ctx, getTradeStats, userID)
	var i GetTradeStatsRow
	err := row.Scan(
		&i.TotalTrades,
		&i.OpenTrades,
		&i.ClosedTrades,
		&i.Wins,
		&i.Losses,
		&i.TotalPnl,
		&i.AvgPnl,
		&i.AvgWin,
		&i.AvgLoss,
		&i.TpCount,
		&i.SlCount,
		&i.TimeStopCount,
		&i.PartialCount,
		&i.ManualCount,
		&i.UnknownCount,
	)
	return &i, err
}

const insert = `-- name: Insert :one
INSERT INTO user_settings (
    chatid, name, settings, step, status,premium
) VALUES (
             $1, $2, $3, $4::text, $5, $6
         ) returning id
`

type InsertParams struct {
	Chatid   int64  `db:"chatid"`
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
}

func (q *Queries) Insert(ctx context.Context, db DBTX, arg *InsertParams) (int64, error) {
	row := db.QueryRow(ctx, insert,
		arg.Chatid,
		arg.Name,
		arg.Settings,
		arg.Step,
		arg.Status,
		arg.Premium,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listEnabled = `-- name: ListEnabled :many
SELECT id, chatid, name, settings, step, status, premium
FROM user_settings
WHERE status = true
`

func (q *Queries) ListEnabled(ctx context.Context, db DBTX) ([]*UserSetting, error) {
	rows, err := db.Query(ctx, listEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserSetting
	for rows.Next() {
		var i UserSetting
		if err := rows.Scan(
			&i.ID,
			&i.Chatid,
			&i.Name,
			&i.Settings,
			&i.Step,
			&i.Status,
			&i.Premium,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenTrades = `-- name: ListOpenTrades :many
SELECT
    guid, user_id, inst_id, pos_side, side, timeframe, strategy,
    entry_price, entry_size, entry_at,
    stop_loss, take_profit, leverage,
    open_order_id, algo_id,
    status, created_at, updated_at
FROM trade_history
WHERE user_id = $1 AND status = 'open'
ORDER BY entry_at ASC
`

type ListOpenTradesRow struct {
	Guid        pgtype.UUID        `db:"guid"`
	UserID      int64              `db:"user_id"`
	InstID      string             `db:"inst_id"`
	PosSide     string             `db:"pos_side"`
	Side        string             `db:"side"`
	Timeframe   string             `db:"timeframe"`
	Strategy    string             `db:"strategy"`
	EntryPrice  float64            `db:"entry_price"`
	EntrySize   float64            `db:"entry_size"`
	EntryAt     pgtype.Timestamptz `db:"entry_at"`
	StopLoss    float64            `db:"stop_loss"`
	TakeProfit  float64            `db:"take_profit"`
	Leverage    int32              `db:"leverage"`
	OpenOrderID string             `db:"open_order_id"`
	AlgoID      string             `db:"algo_id"`
	Status      string             `db:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) ListOpenTrades(ctx context.Context, db DBTX, userID int64) ([]*ListOpenTradesRow, error) {
	rows, err := db.Query(ctx, listOpenTrades, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListOpenTradesRow
	for rows.Next() {
		var i ListOpenTradesRow
		if err := rows.Scan(
			&i.Guid,
			&i.UserID,
			&i.InstID,
			&i.PosSide,
			&i.Side,
			&i.Timeframe,
			&i.Strategy,
			&i.EntryPrice,
			&i.EntrySize,
			&i.EntryAt,
			&i.StopLoss,
			&i.TakeProfit,
			&i.Leverage,
			&i.OpenOrderID,
			&i.AlgoID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTrades = `-- name: ListRecentTrades :many
SELECT
    guid, user_id, inst_id, pos_side, side, timeframe, strategy,
    entry_price, entry_size, entry_at,
    stop_loss, take_profit, leverage,
    open_order_id, algo_id,
    exit_price, exit_size, exit_at,
    realized_pnl, realized_pnl_pct, close_reason,
    status, created_at, updated_at
FROM trade_history
WHERE user_id = $1
ORDER BY entry_at DESC
LIMIT $2
`

type ListRecentTradesParams struct {
	UserID int64 `db:"user_id"`
	Limit  int32 `db:"limit"`
}

func (q *Queries) ListRecentTrades(ctx context.Context, db DBTX, arg *ListRecentTradesParams) ([]*TradeHistory, error) {
	rows, err := db.Query(ctx, listRecentTrades, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TradeHistory
	for rows.Next() {
		var i TradeHistory
		if err := rows.Scan(
			&i.Guid,
			&i.UserID,
			&i.InstID,
			&i.PosSide,
			&i.Side,
			&i.Timeframe,
			&i.Strategy,
			&i.EntryPrice,
			&i.EntrySize,
			&i.EntryAt,
			&i.StopLoss,
			&i.TakeProfit,
			&i.Leverage,
			&i.OpenOrderID,
			&i.AlgoID,
			&i.ExitPrice,
			&i.ExitSize,
			&i.ExitAt,
			&i.RealizedPnl,
			&i.RealizedPnlPct,
			&i.CloseReason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :exec
UPDATE user_settings
SET  name = $1, settings = $2, step = $3::text, status = $4,premium = $5
WHERE chatid = $6
`

type UpdateParams struct {
	Name     string `db:"name"`
	Settings []byte `db:"settings"`
	Step     string `db:"step"`
	Status   bool   `db:"status"`
	Premium  bool   `db:"premium"`
	Chatid   int64  `db:"chatid"`
}

func (q *Queries) Update(ctx context.Context, db DBTX, arg *UpdateParams) error {
	_, err := db.Exec(ctx, update,
		arg.Name,
		arg.Settings,
		arg.Step,
		arg.Status,
		arg.Premium,
		arg.Chatid,
	)
	return err
}
